services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin123'
      MYSQL_DATABASE: 'diet-control'
      MYSQL_ROOT_PASSWORD: 'admin123'
    ports:
      - "3307:3306"
    expose:
      - '3306'
    volumes:
      - /home/ricardocr/formacaoaws/vsc/rocketseat/python/baseintermediario/nivel2/projetoNivel2Python/mysql:/var/lib/mysql